---
- name: Install Server Basics
  apt: pkg={{ item }} update_cache=true
  with_items:
    - unattended-upgrades
    - wget
    - curl
    - htop
    - tmux
  sudo: true

- name: Create logs directory
  file: path=/home/ubuntu/logs state=directory

- name: Copy json.sh
  copy: src=./json.sh dest=/usr/local/sbin/
  sudo: true

- name: Copy authorized_keys
  copy: src=./authorized_keys dest=/home/ubuntu/.ssl/

- name: Check if host keys have been updated
  stat: path=/home/ubuntu/.host-keys-updated
  register: host_keys

- name: Update host keys
  shell: ssh-keygen -A
  sudo: true
  when: not host_keys.stat.exists
  register: host_keys_updated

- name: Add .host-keys-updated
  file: path=/home/ubuntu/.host-keys-updated state=touch
  when: host_keys_updated is defined and host_keys_updated.stdout is defined
