---
- name: Install Server Basics
  apt: pkg={{ item }} update_cache=true
  with_items:
    - unattended-upgrades
    - wget
    - curl
    - htop
    - tmux

- name: Create logs directory
  file: path=/home/ubuntu/logs state=directory
