---

- name: Set Postfix option hostname
  debconf: name=postifx question="postfix/mailname" value="{{domain}}" vtype="string"

- name: Set Postfix option type as internet site
  debconf: name=postfix question="postfix/main_mailer_type" value="'Internet Site'" vtype="string"

- name: Install Server Basics
  apt: pkg={{ item }} update_cache=true
  with_items:
    - unattended-upgrades
    - fail2ban
    - wget
    - curl
    - htop
    - tmux
    - logwatch
  sudo: true

- name: Create logs directory
  file: path=/home/ubuntu/logs state=directory

- name: Check if host keys have been updated
  stat: path=/home/ubuntu/.host-keys-updated
  register: host_keys

- name: Update host keys
  shell: ssh-keygen -A
  sudo: true
  when: not host_keys.stat.exists
  register: host_keys_updated

- name: Add .host-keys-updated
  file: path=/home/ubuntu/.host-keys-updated state=touch
  when: host_keys_updated is defined and host_keys_updated.stdout is defined

- name: Set up user mail aliases
  lineinfile: >
    dest=/etc/aliases
    line="{{ item }}: root"
    regexp="\b{{ item }}:"
  sudo: yes
  with_items:
    - ubuntu
  notify: Rebuild mail aliases

- name: Set root email
  lineinfile: >
    dest=/etc/aliases
    line="root:hpowers@***REMOVED***.com"
    regexp="\b{{ item }}:"
  sudo: yes
  notify: Rebuild mail aliases

- name: Make logwatch mail daily
  cron: name="logwatch" minute="0" hour="0" job="/usr/sbin/logwatch --output mail --mailto hpowers@***REMOVED***.com --detail high"
