---
- name: Config file is present
  template:
    src: nginx.conf.j2
    dest: /home/ubuntu/nginx.conf
    force: true
  when: proxy is not defined
  notify:
    - Restart nginx

- name: Proxy config file is present
  template:
    src: nginx-proxy.conf.j2
    dest: /home/ubuntu/nginx.conf
    force: true
  when: proxy is defined
  notify:
    - Restart nginx

- name: Elasticsearch config file is present
  template:
    src: nginx-elasticsearch.conf.j2
    dest: /home/ubuntu/nginx.conf
    force: true
  when: elasticsearch is defined
  notify:
    - Restart nginx


- name: Template file is present
  template:
    src: nginx.tmpl.j2
    dest: /home/ubuntu/nginx.tmpl
    force: true
  notify:
    - Restart nginx

- name: Create Error Pages dir
  file: dest=/home/ubuntu/error_pages mode=0755 state=directory
  register: errordir

- name: Upload maintenance page
  when: errordir|success
  copy: 
    content: "{{ maintenance_html }}"
    dest: /home/ubuntu/error_pages/maintenance.html

- name: Copy boot task
  copy: src=./start-on-boot.sh dest=/home/ubuntu mode=0777
  register: nginx_boot

- name: Cron job for boot task
  cron: name="nginx on reboot" special_time=reboot job="/home/ubuntu/start-on-boot.sh"

- name: Nginx and docker gen are running
  command: /home/ubuntu/start-on-boot.sh
  when: nginx_boot|success
