---
elasticsearch_user: elasticsearch
elasticsearch_group: elasticsearch
elasticsearch_download_url: https://download.elasticsearch.org/elasticsearch/elasticsearch
elasticsearch_version: 1.7.3
elasticsearch_apt_java_package: oracle-java7-installer
elasticsearch_install_java: "true"
elasticsearch_java_opts: "-XX:-UseSuperWord"
elasticsearch_apt_dependencies:
  - htop
  - ntp
  - unzip
elasticsearch_max_open_files: 65535
elasticsearch_home_dir: /usr/share/elasticsearch
elasticsearch_plugin_dir: /usr/share/elasticsearch/plugins
elasticsearch_log_dir: /var/log/elasticsearch
elasticsearch_data_dir: /var/lib/elasticsearch
elasticsearch_work_dir: /tmp/elasticsearch
elasticsearch_conf_dir: /etc/elasticsearch
elasticsearch_pid_dir: /var/run
elasticsearch_service_startonboot: no
elasticsearch_timezone: "America/New_York"

#elasticsearch_http_cors_enabled: "false"
elasticsearch_service_state: started

# Non-Elasticsearch Defaults
apt_cache_valid_time: 300 # seconds between "apt-get update" calls.

elasticsearch_heap_size: 1g
elasticsearch_max_locked_memory: unlimited

elasticsearch_cluster_name: elasticsearch-oz
elasticsearch_node_name: elasticsearch-oz-node
elasticsearch_node_max_local_storage_nodes: 1
elasticsearch_index_mapper_dynamic: "true"
elasticsearch_memory_bootstrap_mlockall: "true"
elasticsearch_gateway_type: local
elasticsearch_gateway_recover_after_nodes: 1
elasticsearch_gateway_recover_after_time: 2m
elasticsearch_gateway_expected_nodes: 1
elasticsearch_discovery_zen_minimum_master_nodes: 1
elasticsearch_discovery_zen_ping_timeout: 30s
elasticsearch_discovery_zen_ping_multicast_enabled: "true"
elasticsearch_misc_auto_create_index: "true"
elasticsearch_misc_query_bool_max_clause_count: 4096

elasticsearch_misc_disable_delete_all_indices: "true"
