- name: Container is running
  docker:
    name: netdata
    image: titpetric/netdata
    ports:
      - 19999:19999
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
    cap_add:
      - "SYS_PTRACE"
