---
- name: Config directory is present
  file: dest=/home/ubuntu/config mode=0777 state=directory
  register: configdir

- name: Config files are present
  when: configdir|success
  no_log: True
  copy:
    content: "{{ item.value }}"
    dest: /home/ubuntu/config/{{ item.key }}
  with_dict: "{{configs}}"
  register: configcopy

- name: Config files are pretty
  when: configcopy|success
  no_log: True
  command: bash -c "for file in *; do d=$(cat $file); echo $d | python -m json.tool > $file; done"
  args:
    chdir: /home/ubuntu/config
