---
- name: Create SSL Directry
  file: dest=/home/ubuntu/ssl mode=0755 state=directory
  register: ssldir

- name: Upload Unencrypted SSL Files
  when: ssldir|success
  no_log: True
  copy:
    content: "{{ item.value }}"
    dest: /home/ubuntu/ssl/{{ item.key }}
  with_dict: "{{ ssl }}"
