---
- name: Create SSL Directry
  file: dest=/home/ubuntu/ssl mode=0755 state=directory
  register: ssldir

- name: Upload Unencrypted SSL Files
  when: ssldir|success
  copy:
    content: "{{ item.value }}"
    dest: /home/ubuntu/ssl/{{ item.key }}
  with_dict: "{{ ssl }}"
  no_log: True

- name: Create htpasswd Directory
  file: dest=/home/ubuntu/htpasswd mode=0755 state=directory
  register: htpasswddir

- name: Upload Unencrypted SSL Files
  when: htpasswddir|success
  copy:
    content: "{{ item.value }}"
    dest: /home/ubuntu/htpasswd/{{ item.key }}
  with_dict: "{{ htpasswd }}"
  no_log: True
