- name: Config file is present
  copy:
    content: "{{ hubot_config_json }}"
    dest: /home/ubuntu/config.json
  no_log: True

- name: Create hubot_certs directory
  file: dest=/home/ubuntu/hubot_certs mode=0755 state=directory
  register: hubotcertsdir

- name: Certs are present
  copy:
    content: "{{ item.value }}"
    dest: /home/ubuntu/hubot_certs/{{ item.key }}
  with_dict: "{{ hubot_certs }}"
  when: hubotcertsdir|success
  no_log: True

- name: Container is running
  docker:
    name: hubot
    image: fijimunkii/hubot
    volumes:
      - "/home/ubuntu/config.json:/usr/src/app/config.json"
      - "/home/ubuntu/hubot_certs:/usr/src/app/certs"
    env:
      REDIS_URL: "redis://{{ hubot_redis_url }}/hubot"
      HUBOT_AUTH_ADMIN: "{{ hubot_auth_admin }}"
      HUBOT_GITHUB_ORG: "{{ hubot_github_org }}"
      HUBOT_GITHUB_TOKEN: "{{ hubot_github_token }}"
      HUBOT_SLACK_TOKEN: "{{ hubot_slack_token }}"
      HUBOT_SSH_KEY: "{{ hubot_ssh_key }}"
      HUBOT_NAME: "{{ hubot_name }}"
      VIRTUAL_HOST: "hubot.{{ group_names[0] }}"
    log_opt:
      tag: "app/fijimunkii/hubot/master"
  no_log: True
