---
- name: Add docker apt-repository
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' update_cache=yes state=present
  sudo: true

- name: Is docker installed?
  shell: dpkg-query -W 'lxc-docker'
  ignore_errors: true
  changed_when: false
  register: is_docker_installed

- name: Install docker
  apt: name=lxc-docker state=present force=true
  sudo: true
  when: is_docker_installed|failed
  register: docker_installed

- name: Allow sudoless docker
  command: gpasswd -a ubuntu docker
  sudo: true
  when: docker_installed is defined and docker_installed.stdout is defined

- name: Reboot server
  command: shutdown -r now "Reboot triggered by Ansible"
  async: 0
  poll: 0
  ignore_errors: true
  sudo: true
  when: docker_installed is defined and docker_installed.stdout is defined
  register: post_kernal_rebooted

- name: Wait for server to reboot
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=1
      timeout=300
  sudo: false
  when: docker_installed is defined and docker_installed.stdout is defined

- name: Install pip
  apt: name=python-pip state=present
  sudo: true

- name: Install docker-compose
  pip:
    name: docker-compose
    state: present
  sudo: true

- name: Docker syslog
  copy:
    src: docker_syslog
    dest: /etc/default/docker
  sudo: true
  when: logstash is not defined and docker_dir is not defined
  register: copy_result1

- name: Docker syslog with dir
  copy:
    src: docker_syslog_dir
    dest: /etc/default/docker
  sudo: true
  when: logstash is not defined and docker_dir is defined
  register: copy_result2

- name: Docker service is restarted
  shell: service docker restart
  when: copy_result1|changed or copy_result2|changed
  notify:
    - Restart nginx
  sudo: true

- name: Docker cleanup script is copied
  copy: src=cleanup_docker.sh dest=~/.cleanup_docker.sh mode=0777
  register: docker_cleanup

- name: Cron job for docker cleanup
  cron: name="check dirs" minute="0" hour="0" job="/home/ubuntu/.cleanup_docker.sh"
  when: docker_cleanup is defined
